name: CI Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  desktop:
    uses: ./.github/workflows/_build-desktop.yml

  android:
    uses: ./.github/workflows/_build-mobile.yml
